### ISSUE TITLE
Using a mixin causes inaccurate reporting of newlineAfterBlock

### ISSUE THREAD

**Issue by deanc** [lesshint/lesshint#520]
**Which version of `lesshint` are you using?** 6.3.2

**How are you running `lesshint`? CLI, Node.js API, Grunt/Gulp plugin?** gulp-lesshint

**What's your `.lesshintrc` configuration?**

```js
{
  "excludedFiles": ["_mixins.less", "_typography.less"],
  "propertyOrdering": "centric",
  "hexNotation": "uppercase",
  "singleLinePerSelector": false,
  "zeroUnit": {
    "style": "no_unit"
  },
  "importPath": {
    "leadingUnderscore": true
  }
}

```

**If you're reporting a bug, please show us some code that's failing.**

```less
.something {
  display: block;
  .font-size(18); /* comes from another file */
}
```

**What did you expect to happen?** Nothing

**What's the actual result?** `Warning: test.less: line 3, col 3, newlineAfterBlock: All blocks should be followed by a new line.`

**Would you be interested in submitting a PR for this issue?** Not sure I would know how to fix :)

**Comment by jwilsson** [comment]
This should be fixed in `6.3.3`.

**Comment by deanc** [comment]
Thank you @jwilsson . I will test as soon as yarn spots the new version.

**Comment by deanc** [comment]
@jwilsson I'm pretty sure I upgraded (`yarn upgrade lesshint` - although I am using it through the gulp plugin). I checked `yarn.lock` and saw 6.3.3 in there, so it looks to be installed. But i'm still getting the errors, but now in different places.

The example in the original post is fine. But this now gives an error:

```
.something {
  display: block;
  .font-size(18);
  .fontMedium;
}
```
Gives the error:

`Warning: test.less: line 3, col 3, newlineAfterBlock: All blocks should be followed by a new line.`

I also see lots of weird errors where I clearly don't have a mixin in use. 

For example in my `variables.less`:

```
@columnWidth: 60px;
@gutterWidth: 57px;

@desktop: 1400px;
@tablet: 1024px;
@mobile: 720px;

// colors
@bodyBackground: #F4F2EF;
@bodyForeground: #373737;

@norr3Blue: #175E6F;

@green: #4FA389;
@orange: #FF9662;
@pink: #FFBCBD;
@yellow: #FFDD84;

@tabletBreakPoint: @tablet - 1px;
```

Error: `Warning: variables.less: line 1, col 1, newlineAfterBlock: All blocks should be followed by a new line.`

**Comment by jwilsson** [comment]
@deanc Please check with `6.3.5`, that should take care of both issues.

I decided to refactor the whole rule, hence the new errors. Thanks for working through them with me!

**Comment by deanc** [comment]
Thanks @jwilsson - I'm still getting some related issues. Here's another test-case:

```less
@sectionPadding: 8em;

.homepage-section {
    padding-left: 15%;
    display: flex;
    width: 100%;
    max-width: @desktop;
    margin: 0 auto;
    position: relative;

    .side {
        width: 200px;
        padding: @sectionPadding 2em;
        outline: 1px solid red;

        .label {
            transform: rotate(90deg);
            transform-origin: 0;
            .font-size(24);
        }
    }
    .main {
        position: relative;
        flex: 1;

        > p:last-child {
          margin-bottom: 0;
        }
    }
}
```

Note how it's correctly reporting. As soon as I add a new line it gives this instead: `Warning: test.less: line 22, col 4, trailingWhitespace: There shouldn't be any trailing whitespace.`

**Comment by deanc** [comment]
Here's another case where it has issues:

```less
@import 'base/variables';
@import 'base/mixins';
@import 'base/typography';
```

Gives: 
```
Warning: test.less: line 1, col 1, newlineAfterBlock: All blocks should be followed by a new line.
Warning: test.less: line 2, col 1, newlineAfterBlock: All blocks should be followed by a new line.
```

**Comment by jwilsson** [comment]
@deanc Your first case might be correct though (GitHub seems to strip trailing whitespace), are there any trailing whitespace on that line?

The second case is definitely a bug, though. I'll take a look.

**Comment by jwilsson** [comment]
@deanc With `6.3.6` `@import` s shouldn't be reported anymore.
